service: smartthings-yale-smart-alarm # NOTE: update this with your service name
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  memorySize: 128
  environment:
    APP_ID: ${param:appId}
    CLIENT_ID: ${param:clientId}
    CLIENT_SECRET: ${param:clientSecret}
    YALE_USERNAME: ${param:yaleUsername}
    YALE_PASSWORD: ${param:yalePassword}

functions:
  yalealarm:
    handler: handler.handle

plugins:
  - serverless-plugin-typescript