service: smartthings-yale-smart-alarm # NOTE: update this with your service name
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  memorySize: 128
  environment:
    APP_ID: ${param:appId}
    CLIENT_ID: ${param:clientId}
    CLIENT_SECRET: ${param:clientSecret}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ['dynamodb:PutItem', 'dynamodb:GetItem', 'dynamodb:DeleteItem']
          Resource: 
          - 'Fn::Join': [':', ['arn:aws:dynamodb:eu-west-1', { Ref: 'AWS::AccountId' }, 'table/SmartThingsYaleTokens']]
          
functions:
  yalealarm:
    handler: handler.handle

resources: # CloudFormation template syntax from here on.
      Resources:
        usersTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: SmartThingsYaleTokens
            AttributeDefinitions:
              - AttributeName: installedAppId
                AttributeType: S
            KeySchema:
              - AttributeName: installedAppId
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

plugins:
  - serverless-plugin-typescript